create table if not exists players (
  id text primary key,
  username text not null,
  credits integer not null default 0,
  equipped_skin text not null default 'default',
  best integer not null default 0,
  best_daily integer not null default 0,
  level_progress integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists scores (
  id bigint generated by default as identity primary key,
  player_id text not null references players(id) on delete cascade,
  username text not null,
  score integer not null check (score >= 0),
  mode text not null,
  level integer,
  duration_seconds numeric,
  created_at timestamptz not null default now()
);

create index if not exists scores_mode_score_idx on scores(mode, score desc);
create unique index if not exists players_username_lower_idx on players(lower(username));

create table if not exists player_skins (
  player_id text not null references players(id) on delete cascade,
  skin_id text not null,
  unlocked_at timestamptz not null default now(),
  primary key (player_id, skin_id)
);

create table if not exists player_levels (
  player_id text not null references players(id) on delete cascade,
  level integer not null,
  completed_at timestamptz not null default now(),
  primary key (player_id, level)
);

create table if not exists player_missions (
  player_id text not null references players(id) on delete cascade,
  mission_key text not null,
  progress integer not null default 0,
  done boolean not null default false,
  updated_at timestamptz not null default now(),
  primary key (player_id, mission_key)
);

create table if not exists daily_scores (
  id bigint generated by default as identity primary key,
  player_id text not null references players(id) on delete cascade,
  challenge_date date not null,
  username text not null,
  score integer not null check (score >= 0),
  duration_seconds numeric,
  created_at timestamptz not null default now(),
  unique(player_id, challenge_date)
);

create index if not exists daily_scores_date_score_idx on daily_scores(challenge_date, score desc);


-- KV compatível com o adapter do jogo.
create table if not exists public.kv_store (
  key text primary key,
  value text not null,
  updated_at timestamptz not null default now()
);

create index if not exists kv_store_key_prefix_idx on public.kv_store(key text_pattern_ops);

-- O ranking é público para leitura e o jogo pode gravar suas próprias chaves.
-- IMPORTANTE: isto deixa o ranking funcional, mas não é proteção anti-cheat de nível servidor.
-- Para produção competitiva, migre o submitScore para uma Edge Function/RPC que valide a corrida no servidor.
alter table public.kv_store enable row level security;
drop policy if exists "public read kv" on public.kv_store;
drop policy if exists "public insert kv" on public.kv_store;
drop policy if exists "public update kv" on public.kv_store;
create policy "public read kv" on public.kv_store for select to anon, authenticated using (true);
create policy "public insert kv" on public.kv_store for insert to anon, authenticated with check (true);
create policy "public update kv" on public.kv_store for update to anon, authenticated using (true) with check (true);
